name: Generate manifest

on:
  push:
    branches: [ "main" ]   # или любая твоя рабочая ветка

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node generateManifest.js

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifest.json
          git commit -m "Update manifest [skip ci]" || echo "No changes"
          git push
